apiVersion: apps/v1
kind: Deployment
metadata:
  name: task2-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: task2
  template:
    metadata:
      labels:
        app: task2
    spec:
      containers:
      - name: task2-container
        image: kosier/webapplication:2.1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 2
