apiVersion: apps/v1
kind: Deployment
metadata:
  name: zad2-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: zad2
  template:
    metadata:
      labels:
        app: zad2
    spec:
      containers:
      - name: zad2-container
        image: piotrtokarski/webapplication:1.0
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 2
